server:
  port: 8311

spring:
  datasource:
    url: jdbc:mysql://192.168.50.20:3306/iam?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: sa
    password: password
    mybatis:
        # 配置mapper的扫描，找到所有的mapper.xml映射文件
      mapperLocations: classpath:mapper/*.xml