server:
  port: 8028

spring:
  datasource:
    url: jdbc:mysql://172.16.10.79:3306/mytestdb?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: sa
    password: password
    mybatis:
        # 配置mapper的扫描，找到所有的mapper.xml映射文件
      mapperLocations: classpath:mapper/*.xml