server:
  port: 9031

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.50.20:8848
    gateway:
      routes:
        - id: user_service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: order_service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
